<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Tests\Common.Tests.csproj" />
      <ProjectReference Include="..\Y2021D01\Y2021D01.csproj" />
    </ItemGroup>

</Project>
